// Generated by https://quicktype.io

import 'dart:convert';

import 'package:app_restaurante/src/models/platoModel.dart';

class Historialenviados {
  List platos;
  String nombre;
  String id;
  int valor;
  String usuarioId;
  String estado;
  String direccionId;
  String fecha;
  int numero;

  Historialenviados({
    this.nombre,
    this.platos,
    this.id,
    this.valor,
    this.usuarioId,
    this.estado,
    this.direccionId,
    this.fecha,
    this.numero,
  });

  Historialenviados.fromJsonMap(Map<String, dynamic> json) {
    platos = json["platos"];
    nombre = json["nombre"];
    id = json['_id'];
    valor = json['valor'];
    usuarioId = json['usuario_id'];
    estado = json['estado'];
    direccionId = json['direccion_id'];
    fecha = json['fecha'];
    numero = json['numero'];
  }
}

class Historialdelospedidos {
  // ignore: deprecated_member_use
  final List<Historialenviados> historialdepedidos = new List();
  Historialdelospedidos();
  Historialdelospedidos.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final historial = new Historialenviados.fromJsonMap(item);
      historialdepedidos.add(historial);
    }
  }
}
